apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      runtimeClassName: kata-qemu
      automountServiceAccountToken: false
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: docker.io/library/busybox:1.37.0
          command: [sh, -c, "mkdir -p /tmp/www; echo 'Kata on Chopin' > /tmp/www/index.html; httpd -f -p 8080 -h /tmp/www"]
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: applications
spec:
  selector:
    app: web
  ports:
    - port: 8080
      targetPort: 8080
