#!/usr/bin/env bash
# Nix-owned credential provisioning only. Flux installation and root sync are
# K3s manifests generated by Nix; this never writes bootstrap files to Git.
set -euo pipefail
[[ $EUID == 0 ]] || { echo "Run on the node as root." >&2; exit 1; }
task_age_file=${1:?Usage: provision-flux-credentials.sh /external/age/keys.txt [external/git-auth-directory]}
task_git_dir=${2:-}
[[ $task_age_file != /nix/store/* ]] || { echo "Refusing a Nix store identity." >&2; exit 1; }
[[ -f $task_age_file ]] || { echo "Missing external age identity." >&2; exit 1; }
# Validation prints only the public recipient, and discards it.
age-keygen -y "$task_age_file" >/dev/null 2>&1 || { echo "Invalid age identity." >&2; exit 1; }
[[ $(stat -c '%u' "$task_age_file") == 0 ]] || { echo "Age identity must be owned by root." >&2; exit 1; }
[[ $(stat -c '%a' "$task_age_file") == 600 || $(stat -c '%a' "$task_age_file") == 400 ]] || {
  echo "Age identity must have mode 0600 or 0400." >&2; exit 1;
}
k() { k3s kubectl "$@"; }
for ((task_attempt=0; task_attempt<60; task_attempt++)); do
  if k get namespace flux-system >/dev/null 2>&1; then break; fi
  sleep 2
done
k wait --for=condition=Established --timeout=180s \
  crd/gitrepositories.source.toolkit.fluxcd.io \
  crd/kustomizations.kustomize.toolkit.fluxcd.io \
  crd/helmreleases.helm.toolkit.fluxcd.io
# Private material exists only in this pipe and the encrypted cluster datastore.
k create secret generic sops-age -n flux-system --from-file=age.agekey="$task_age_file" \
  --dry-run=client -o json | jq '.metadata.labels["homelab/owner"]="nix"' | \
  k apply --server-side --field-manager=nix-bootstrap -f - >/dev/null
if [[ -n $task_git_dir ]]; then
  [[ $task_git_dir != /nix/store/* && -f $task_git_dir/username && -f $task_git_dir/password ]] || {
    echo "Git auth must be an external directory with username and password files." >&2; exit 1;
  }
  for task_credential in "$task_git_dir/username" "$task_git_dir/password"; do
    [[ $(stat -c '%u' "$task_credential") == 0 && ( $(stat -c '%a' "$task_credential") == 600 || $(stat -c '%a' "$task_credential") == 400 ) ]] || {
      echo "Git credential files must be root-owned with mode 0600 or 0400." >&2; exit 1;
    }
  done
  k create secret generic flux-git-auth -n flux-system \
    --from-file=username="$task_git_dir/username" --from-file=password="$task_git_dir/password" \
    --dry-run=client -o json | jq '.metadata.labels["homelab/owner"]="nix"' | \
    k apply --server-side --field-manager=nix-bootstrap -f - >/dev/null
fi
k wait -n flux-system --for=condition=Available --timeout=300s \
  deployment/source-controller deployment/kustomize-controller deployment/helm-controller
k get gitrepository homelab -n flux-system >/dev/null
k get kustomization cluster -n flux-system >/dev/null
echo "Flux credentials provisioned. Nix owns bootstrap; Git owns applications."
