apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: kube-system
data:
  calico_backend: vxlan
  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "1.0.0",
      "plugins": [
        {
          "type": "calico",
          "readiness_gates": ["http://localhost:9099/readiness"],
          "policy_setup_timeout_seconds": 30,
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {"type": "calico-ipam"},
          "policy": {"type": "k8s"},
          "kubernetes": {"kubeconfig": "__KUBECONFIG_FILEPATH__"}
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        }
      ]
    }
